window.lookupTable = [
    ["SageMaker($)", "locationAI"],
    ["OpenSearch Service($)", "opensearch"],
    ["Relational Database Service($)", "databases"],
    ["CloudWatch($)", "cloudwatch"],
    ["Support (Business)($)", "support"],
    ["S3($)", "s3"],
    ["Kinesis($)", "other"],
    ["Savings Plans for Compute usage($)", "compute"],
    ["EC2-Other($)", "compute"],
    ["API Gateway($)", "compute"],
    ["GuardDuty($)", "other"],
    ["DynamoDB($)", "other"],
    ["MemoryDB($)", "other"],
    ["Elastic Load Balancing($)", "other"],
    ["Managed Service for Prometheus($)", "other"],
    ["Key Management Service($)", "other"],
    ["Elastic Container Service for Kubernetes($)", "other"],
    ["VPC($)", "other"],
    ["Managed Grafana($)", "other"],
    ["Kinesis Firehose($)", "other"],
    ["ElastiCache($)", "other"],
    ["Cognito($)", "other"],
    ["Inspector($)", "other"],
    ["Secrets Manager($)", "other"],
    ["Directory Service($)", "other"],
    ["Lambda($)", "compute"],
    ["EC2-Instances($)", "compute"],
    ["EC2 Container Registry (ECR)($)", "compute"],
    ["Pinpoint($)", "other"],
    ["CodeWhisperer($)", "other"],
    ["Route 53($)", "other"],
    ["SES($)", "other"],
    ["Config($)", "other"],
    ["SQS($)", "other"],
    ["Athena($)", "other"],
    ["DMS($)", "other"],
    ["Registrar($)", "other"],
    ["Elastic File System($)", "other"],
    ["SNS($)", "other"],
    ["IoT 1 Click($)", "other"],
    ["Cloud Map($)", "other"],
    ["CloudWatch Events($)", "other"],
    ["CloudFront($)", "other"],
    ["Backup($)", "other"],
    ["CloudShell($)", "other"],
    ["Step Functions($)", "other"],
    ["CloudTrail($)", "other"],
    ["Glue($)", "other"],
    ["X-Ray($)", "other"],
    ["Elastic Container Service($)", "other"],
    ["Tax($)", "other"],
    ["Service Catalog($)", "other"],
    ["CloudFormation($)", "other"],
    ["QuickSight($)", "other"],
    ["Device Farm($)", "other"],
    ["Cost Explorer($)", "other"],
    ["Systems Manager($)", "other"],
    ["Linux 2 AMI with Support by Supported Images($)", "other"]
];